# paraphraser config

model_id='./models/qwen'

device_map='auto'
max_new_tokens=200
do_sample=true
temperature=0.1
repetition_penalty=1.1

prompt='''Please paraphrase the following text while ensuring that the core meaning of the original is preserved. Use different vocabulary, sentence structures, and expressions. The paraphrased text should be fluent and natural, avoiding direct copying of phrases or sentence structures from the original.
Paraphrasing Requirements:
- Maintain the core information and intent of the original text.
- Use synonyms, different sentence structures, or alternative expressions.
- Ensure the paraphrased text is coherent and grammatically correct.
- Avoid introducing new information or omitting important details.
- Original Text are braketed in `###`

Original Text:
###{}###

Paraphrased Text:

'''
